from aetheropt.solvers.classical.classical_sa import ClassicalSA
from aetheropt.solvers.classical.highs_solver import HighsSolver
from aetheropt.solvers.quantum_inspired.quantum_inspired_sa import QuantumInspiredSA
from aetheropt.solvers.quantum.qaoa import QAOALocalSolver
from aetheropt.solvers.quantum_inspired.simulated_bifurcation import SimulatedBifurcationSolver
from aetheropt.solvers.registry import get_solver
